### ISSUE TITLE
Convert to .sublime-syntax?

### ISSUE THREAD

**Issue by vinyldarkscratch** [andik/IDL-Syntax#7]
It's quite nice to have a syntax definition format that works across multiple editors, but it appears that support for the `.tmLanguage` syntax is being phased out in editors (Atom [mentions](https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/) they "intend to phase [TextMate grammar definitions] out over time," and Sublime Text prefers `.sublime-syntax` files -- VSCode still uses `.tmLanguage` though).

If the scope is just Sublime Text, and not other editors, I'm wondering: would it be more reasonable to convert from `.tmLanguage` to `.sublime-syntax`?  Sublime Text now has a quick convert function (`Tools > Developer > New Syntax from ***.tmLanguage...`), though a few of the patterns (`#angle_brackets`, `#special_blocks`, and `#constructor`) are undefined so the converter crashes.

**Comment by andik** [comment]
The Sublime-Syntax Format is different from the .tmLanguage Format in many ways.
It may be superior, but I don't have time/interest converting IDL-Syntax. 
Sorry.

**Comment by andik** [comment]
Sorry,
If the converter works, I'm happy to add this to the repository, but IDL-Syntax is based on Sublime's old C-Syntax and this is fairly complex. Sublime-Syntax has a push-pop Model for parsing nested structures, while tmLanguage is based on Nested Patterns.
I'm pretty sure, that this would need a full re-creation of IDL-Syntax to work properly.
And I don't have time/interest to invest into this.

**Comment by vinyldarkscratch** [comment]
That's alright!  I was primarily asking because I wanted to contribute to improve the WebIDL syntax highlighting, and .sublime-syntax looked far friendlier to work with.  Alas, since there are numerous things in MS IDL that are not in WebIDL, I ended up starting fresh and [making my own syntax highlighting](https://github.com/vinyldarkscratch/WebIDL-Sublime) for WebIDL specifically.

**Comment by andik** [comment]
Your package looks really good. I added a link to my Readme. 
Thank you for mentioning the converter, I didn't know.
Maybe I'll have a look at it to convert my MSIDL sometimes.
